# Auto-assign configuration for PR automation
# Automatically assigns reviewers to pull requests

# Add reviewers to pull requests
addReviewers: true

# Add assignees to pull requests
addAssignees: false

# Number of reviewers to add
numberOfReviewers: 2

# List of reviewers (GitHub usernames)
# Customize this list for your organization
reviewers:
  - reviewer1
  - reviewer2
  - reviewer3

# Assign based on file patterns (optional)
# filePathMapping:
#   "**/*.js":
#     - javascript-team-member
#   "**/*.py":
#     - python-team-member
#   "**/*.go":
#     - go-team-member

# Skip adding reviewers if PR already has reviewers
skipReviewersIfReviewAlreadyExists: true

# Skip adding reviewers if the PR is a draft
skipDraftPR: true

# Use review groups
# reviewGroups:
#   frontend:
#     - frontend-dev-1
#     - frontend-dev-2
#   backend:
#     - backend-dev-1
#     - backend-dev-2
#   devops:
#     - devops-engineer-1
#     - devops-engineer-2

# Use assignee groups
# assigneeGroups:
#   ops:
#     - ops-team-member-1
#     - ops-team-member-2

# Filter labels to skip auto-assignment
# skipKeywords:
#   - wip
#   - work-in-progress
#   - do-not-review

# Run only when specific labels exist
# runOnLabels:
#   - ready-for-review
#   - needs-review
