# Auto-labeler configuration for PR automation
# Automatically labels PRs based on changed files

# Documentation
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'
      - 'LICENSE*'
      - 'README*'

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'pnpm-lock.yaml'
      - 'bun.lockb'
      - 'requirements.txt'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'Pipfile'
      - 'Pipfile.lock'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'go.mod'
      - 'go.sum'
      - 'Cargo.toml'
      - 'Cargo.lock'

# CI/CD
ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '.circleci/**'
      - '.gitlab-ci.yml'
      - 'Jenkinsfile'
      - '.travis.yml'
      - 'azure-pipelines.yml'

# Docker
docker:
  - changed-files:
    - any-glob-to-any-file:
      - '**/Dockerfile*'
      - '**/*.dockerfile'
      - 'docker-compose*.yml'
      - '.dockerignore'

# Configuration
config:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.config.js'
      - '**/*.config.ts'
      - '**/*.config.json'
      - '.env*'
      - '*.toml'
      - '*.yaml'
      - '*.yml'
      - 'tsconfig*.json'

# Tests
test:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.test.*'
      - '**/*.spec.*'
      - '**/test/**'
      - '**/tests/**'
      - '**/__tests__/**'
      - 'jest.config.*'
      - 'vitest.config.*'
      - 'pytest.ini'
      - '.coveragerc'

# Frontend
frontend:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/**/*.{tsx,jsx,css,scss,sass,less}'
      - 'public/**/*'
      - 'assets/**/*'
      - 'styles/**/*'
      - 'components/**/*'

# Backend
backend:
  - changed-files:
    - any-glob-to-any-file:
      - 'api/**/*'
      - 'server/**/*'
      - 'backend/**/*'
      - 'services/**/*'

# Database
database:
  - changed-files:
    - any-glob-to-any-file:
      - '**/migrations/**'
      - '**/seeds/**'
      - '**/*.sql'
      - 'prisma/**'
      - 'schema.prisma'

# Security
security:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/security*.yml'
      - '**/SECURITY.md'
      - '**/.snyk'

# Python
python:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.py'
      - 'setup.py'
      - 'pyproject.toml'

# JavaScript/TypeScript
javascript:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.mjs'
      - '**/*.cjs'

# Go
go:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

# Rust
rust:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'

# Java
java:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.java'
      - 'pom.xml'
      - 'build.gradle'
      - 'build.gradle.kts'
