# ========================================
# Mergeable Bot Configuration Template
# Documentation: https://github.com/mergeability/mergeable
# ========================================
# This is a template file showing the structure for mergeable bot configuration.
# Replace placeholder values with actual configuration based on your needs.
# ========================================

version: 2
mergeable:
  # Recipe A: Example pull request validation
  - when: pull_request.opened, pull_request.edited
    name: PR Title Validation
    validate:
      - do: title
        must_include:
          regex: "^(feat|fix|docs|style|refactor|test|chore):"
          message: "Title must start with a conventional commit type"
    fail:
      - do: comment
        payload:
          body: "Please update the PR title to follow conventional commit format"

  # Recipe B: Example label-based checks
  - when: pull_request.labeled
    name: Label-Based Checks
    filter:
      - do: label
        must_include:
          regex: "(ready|review)"
    validate:
      - do: approvals
        min:
          count: 1
        message: "At least one approval required"
    pass:
      - do: checks
        status: success
    fail:
      - do: comment
        payload:
          body: "This PR needs at least one approval before merging"
