APPLY_FIXES: all
IGNORE_GENERATED_FILES: true
IGNORE_GITIGNORED_FILES: true
PARALLEL: true
ENABLE: BASH,PYTHON,JSON,MARKDOWN,YAML,JAVASCRIPT,TYPESCRIPT,ACTION,DOCKERFILE
DISABLE_LINTERS: REPOSITORY_KICS,REPOSITORY_GRYPE,SPELL_VALE,SPELL_PROSELINT
DISABLE_ERRORS_LINTERS: SPELL_CSPELL,SPELL_LYCHEE
PYTHON_DEFAULT_STYLE: ruff
SHELLCHECK_ARGUMENTS: "-S warning"
SHFMT_ARGUMENTS: "-ln bash -s -i 2 -bn"
FILTER_REGEX_EXCLUDE: '(node_modules|\.git|\.cache|\.venv|dist|build|megalinter-reports)'
