---
# ========================================
# MegaLinter Configuration
# Documentation: https://megalinter.io/latest/configuration/
# ========================================

# ===========================
# Global Settings
# ===========================

# Apply automatic fixes
APPLY_FIXES: all

# Ignore generated and gitignored files
IGNORE_GENERATED_FILES: true
IGNORE_GITIGNORED_FILES: true

# Performance
PARALLEL: true
SHOW_ELAPSED_TIME: true

# Reporting
REPORT_OUTPUT_FOLDER: megalinter-reports
FLAVOR_SUGGESTIONS: false
ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true

# ===========================
# Language/Format Enablement
# ===========================

# Enable specific linters
# Note: CSS handled by Biome, JS/TS handled by Biome
ENABLE: BASH,MAKEFILE,POWERSHELL,PYTHON,CSS,ENV,HTML,JSON,MARKDOWN,XML,YAML,JAVASCRIPT,TYPESCRIPT,JSX,ACTION,DOCKERFILE,EDITORCONFIG

# ===========================
# Disabled Linters
# ===========================

# Completely disabled linters
DISABLE_LINTERS: REPOSITORY_KICS,REPOSITORY_GRYPE,SPELL_VALE,SPELL_PROSELINT

# Linters that run but don't cause failures (reduced list - only non-critical)
DISABLE_ERRORS_LINTERS: SPELL_CSPELL,SPELL_LYCHEE,REPOSITORY_SEMGREP,REPOSITORY_DEVSKIM

# ===========================
# Linter-Specific Configuration
# ===========================

LINTERS:
  # JavaScript/TypeScript - Biome (primary)
  - linter: biome
    descriptor: JAVASCRIPT
    variables:
      JAVASCRIPT_BIOME_CONFIG_FILE: biome.json
      JAVASCRIPT_BIOME_FILE_EXTENSIONS: [".js", ".jsx", ".ts", ".tsx"]
      JAVASCRIPT_BIOME_ARGUMENTS: check --apply

  # CSS - Biome
  - linter: biome
    descriptor: CSS
    variables:
      CSS_BIOME_CONFIG_FILE: biome.json
      CSS_BIOME_FILE_EXTENSIONS: [".css"]

  # YAML Linting - yamllint (validation)
  - linter: yamllint
    variables:
      YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml
      YAML_YAMLLINT_CLI_LINT_MODE: file
      YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(node_modules|\.git|\.cache|megalinter-reports)'

  # YAML Formatting - yamlfmt (primary) and Prettier (fallback)
  - linter: yamlfmt
    descriptor: YAML
    variables:
      YAML_YAMLFMT_CONFIG_FILE: .yamlfmt
      YAML_YAMLFMT_FILE_EXTENSIONS: [".yml", ".yaml"]

  - linter: prettier
    descriptor: YAML
    variables:
      YAML_PRETTIER_CONFIG_FILE: .prettierrc.yml
      YAML_PRETTIER_FILE_EXTENSIONS: [".yml", ".yaml"]
      YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(node_modules|\.git|\.cache)'

  # JSON Linting
  - linter: jsonlint
    variables:
      JSON_JSONLINT_CLI_LINT_MODE: list_of_files
      JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(node_modules|\.git|package-lock\.json|yarn\.lock)'

  # JSON Formatting (Prettier)
  - linter: prettier
    descriptor: JSON
    variables:
      JSON_PRETTIER_CONFIG_FILE: .prettierrc.yml
      JSON_PRETTIER_FILE_EXTENSIONS: [".json", ".json5", ".jsonc"]
      JSON_PRETTIER_FILTER_REGEX_EXCLUDE: '(node_modules|\.git|package-lock\.json)'

  # TOML Formatting
  - linter: taplo
    variables:
      TOML_TAPLO_ARGUMENTS: fmt
      TOML_TAPLO_FILE_EXTENSIONS: [".toml"]

# ===========================
# Tool-Specific Arguments
# ===========================

# ShellCheck (primary config in .shellcheckrc, minimal args here)
SHELLCHECK_ARGUMENTS: "-S warning"
SHELLCHECK_FILTER_REGEX_EXCLUDE: '(node_modules|\.git|\.cache)'

# shfmt (Shell Formatter)
SHFMT_ARGUMENTS: "-ln bash -s -i 2 -bn --apply-ignore"
SHFMT_FILTER_REGEX_EXCLUDE: '(node_modules|\.git|\.cache)'

# Python
PYTHON_DEFAULT_STYLE: ruff
PYTHON_FILTER_REGEX_EXCLUDE: '(node_modules|\.git|\.venv|venv|__pycache__)'

# Markdown
MARKDOWN_FILTER_REGEX_EXCLUDE: '(node_modules|\.git|CHANGELOG\.md)'

# Spell Checker (kept disabled - non-blocking)
SPELL_LYCHEE_DISABLE_ERRORS: true
SPELL_CSPELL_DISABLE_ERRORS: true

# YAML Validator (errors now enabled for quality control)
YAML_V8R_FILE_EXTENSIONS: [".yml", ".yaml", ".toml", ".json", ".jsonc"]

# ===========================
# File Filters
# ===========================

# Global exclusion pattern (standardized across all linters)
FILTER_REGEX_EXCLUDE: '(\.github/workflows|node_modules|\.git|\.cache|\.claude|\.venv|venv|dist|build|coverage|megalinter-reports)'

# File patterns to include
fileio:
  files:
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.json"
    - "**/*.json5"
    - "**/*.jsonc"
    - "**/*.toml"
    - "**/*.properties"
    - "**/*.sh"
    - "**/*.bash"
    - "**/*.py"
    - "**/*.md"

# ===========================
# Exclusions
# ===========================

# Excluded directories
excluded_directories:
  - node_modules
  - .git
  - .cache
  - .claude
  - .venv
  - venv
  - dist
  - build
  - megalinter-reports
  - coverage

# Excluded files
excluded_files:
  - package-lock.json
  - yarn.lock
  - pnpm-lock.yaml
  - poetry.lock
  - Cargo.lock
  - "*.min.js"
  - "*.min.css"
