---
# ========================================
# Prettier Code Formatter Configuration
# Documentation: https://prettier.io/docs/en/configuration.html
# ========================================
# Scope: YAML, JSON, TOML, Markdown formatting
# Note: JS/TS/CSS are handled by Biome (see biome.json)
# YAML formatting shared with yamlfmt (see .yamlfmt)
# Line width standardized to 120 characters across all file types.
# ========================================

# ===========================
# Global Formatting Options
# ===========================

# Line width (standardized across all tools)
printWidth: 120

# Indentation
tabWidth: 2
useTabs: false

# Syntax
semi: false
singleQuote: false
quoteProps: consistent
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always

# Line endings
endOfLine: lf

# Prose wrapping
proseWrap: preserve

# ===========================
# File Type Overrides
# ===========================

overrides:
  # YAML files (workflows, configs, etc.)
  - files: ["*.yml", "*.yaml"]
    options:
      printWidth: 120
      tabWidth: 2
      proseWrap: preserve
      bracketSpacing: true
      singleQuote: false

  # JSON files (configs, package files, etc.)
  - files: ["*.json", "*.json5", "*.jsonc"]
    options:
      printWidth: 120
      tabWidth: 2
      trailingComma: none

  # TOML files (Cargo.toml, pyproject.toml, etc.)
  - files: "*.toml"
    options:
      printWidth: 120
      tabWidth: 2

  # Markdown files (documentation)
  - files: ["*.md", "*.mdx"]
    options:
      printWidth: 80
      proseWrap: always
      tabWidth: 2
