---
# YAML Linting Configuration
# Documentation: https://yamllint.readthedocs.io/

extends: default
locale: en_US.UTF-8

# Directories and files to ignore
ignore: |
  node_modules/
  .git/
  .cache/
  .claude/
  megalinter-reports/
  package-lock.json
  yarn.lock
  pnpm-lock.yaml

# Use gitignore patterns
ignore-from-file: .gitignore

# File patterns to lint
yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint"

rules:
  # Anchors and aliases
  anchors:
    forbid-undeclared-aliases: true
    forbid-duplicated-anchors: true

  # Line length - relaxed for readability
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
    level: warning

  # Syntax rules
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  # Comments
  comments-indentation: disable
  comments:
    min-spaces-from-content: 1
    require-starting-space: true
    level: warning

  # Braces and brackets
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
    level: warning
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
    level: warning

  # Document markers (optional for GitHub Actions)
  document-start: disable
  document-end: disable

  # Empty lines and values
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0
    level: warning
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

  # Hyphens
  hyphens:
    max-spaces-after: 1

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
    level: warning

  # Key rules
  key-duplicates: enable
  key-ordering: disable

  # Line endings
  new-line-at-end-of-file: enable
  new-lines:
    type: unix

  # Values
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: false
  quoted-strings:
    quote-type: any
    required: false
    extra-required: []
    extra-allowed: []
    level: warning
  trailing-spaces: enable
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
    check-keys: false
    level: warning
  float-values: disable
