name: Git Maintenance & Cleanup (Reusable)
"on":
  workflow_call:
    inputs:
      run_gc:
        description: Run git garbage collection
        type: boolean
        default: true
        required: false
      run_prune:
        description: Prune unreachable objects older than specified time
        type: boolean
        default: true
        required: false
      prune_expire:
        description: Expiration time for pruning (e.g., "2.weeks.ago", "1.month.ago")
        type: string
        default: 2.weeks.ago
        required: false
      optimize_repo:
        description: Run repository optimization (repack, etc.)
        type: boolean
        default: true
        required: false
      verify_integrity:
        description: Verify repository integrity with git fsck
        type: boolean
        default: true
        required: false
      cleanup_branches:
        description: Clean up merged and stale remote-tracking branches
        type: boolean
        default: false
        required: false
      branch_retention_days:
        description: Days to keep branches without activity before marking as stale
        type: number
        default: 90
        required: false
      aggressive_gc:
        description: Use aggressive garbage collection (slower but more thorough)
        type: boolean
        default: false
        required: false
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: false
permissions:
  contents: write
  pull-requests: write
jobs:
  maintenance:
    name: Git Repository Maintenance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT || github.token }}
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Repository Statistics (Before)
        id: stats-before
        run: |
          set -euo pipefail
          {
            echo "## Repository Statistics (Before Maintenance)"; echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
          # Extract stats efficiently
          while IFS=': ' read -r key value; do
            case $key in
              count) object_count=$value ;;
              in-pack) pack_count=$value ;;
              size-pack) repo_size=$value ;;
            esac
          done < <(git count-objects -v | grep -E '^(count|in-pack|size-pack):')
          total_branches=$(git branch -r | grep -vc '\->')
          {
            echo "Objects (loose): $object_count"
            echo "Objects (packed): $pack_count"
            echo "Repository size: ${repo_size} KiB"
            echo "Remote branches: $total_branches"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
          {
            echo "object_count=$object_count"
            echo "pack_count=$pack_count"
            echo "repo_size=$repo_size"
          } >> "$GITHUB_OUTPUT"
      - name: Verify Repository Integrity
        if: inputs.verify_integrity
        run: |
          set -euo pipefail
          {
            echo "## Repository Integrity Check"
            echo "Running git fsck..."
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
          if git fsck --full --no-progress 2>&1 | tee -a "$GITHUB_STEP_SUMMARY"; then
            echo "✓ Repository integrity verified successfully" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "⚠ Integrity issues detected - see log above" >> "$GITHUB_STEP_SUMMARY"
          fi
          echo '```' >> "$GITHUB_STEP_SUMMARY"
      - name: Prune Unreachable Objects
        if: inputs.run_prune
        run: |
          set -euo pipefail
          {
            echo "## Pruning Unreachable Objects"
            echo "Removing objects older than: ${{ inputs.prune_expire }}"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
          if output=$(git prune --expire="${{ inputs.prune_expire }}" --progress 2>&1); then
            if [[ -n $output ]]; then
              echo "$output" >> "$GITHUB_STEP_SUMMARY"
            else
              echo "No objects to prune" >> "$GITHUB_STEP_SUMMARY"
            fi
          fi
          echo '```' >> "$GITHUB_STEP_SUMMARY"
      - name: Run Garbage Collection
        if: inputs.run_gc
        run: |
          set -euo pipefail
          echo "## Garbage Collection" >> "$GITHUB_STEP_SUMMARY"
          gc_flags="--prune=now"
          if [[ "${{ inputs.aggressive_gc }}" == "true" ]]; then
            gc_flags="$gc_flags --aggressive"
            echo "Running **aggressive** garbage collection..." >> "$GITHUB_STEP_SUMMARY"
          else
            echo "Running standard garbage collection..." >> "$GITHUB_STEP_SUMMARY"
          fi
          {
            echo '```'
            # shellcheck disable=SC2086
            git gc $gc_flags 2>&1 || :
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
      - name: Optimize Repository
        if: inputs.optimize_repo
        run: |
          set -euo pipefail
          {
            echo "## Repository Optimization"
            echo '```'
            echo "Running git maintenance tasks..."
          } >> "$GITHUB_STEP_SUMMARY"
          git maintenance run --task=loose-objects --task=incremental-repack 2>&1 || :
          {
            echo ""
            echo "Repacking repository with delta compression..."
          } >> "$GITHUB_STEP_SUMMARY"
          git repack -a -d --depth=250 --window=250 2>&1 || :
          echo '```' >> "$GITHUB_STEP_SUMMARY"
      - name: Clean Up Merged Branches
        if: inputs.cleanup_branches
        id: cleanup-branches
        run: |
          set -euo pipefail
          echo "## Branch Cleanup" >> "$GITHUB_STEP_SUMMARY"
          git fetch --prune --prune-tags
          default_branch=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
          current_branch=$(git branch --show-current)
          {
            echo "### Merged Branches"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
          mapfile -t merged < <(git branch -r --merged "origin/$default_branch" | \
            grep -v '\->' | \
            grep -v "origin/$default_branch" | \
            grep -v "origin/$current_branch" | \
            sed 's/origin\///' || :)
          if [[ ${#merged[@]} -gt 0 ]]; then
            printf '%s\n' "${merged[@]}" >> "$GITHUB_STEP_SUMMARY"
            echo "merged_count=${#merged[@]}" >> "$GITHUB_OUTPUT"
          else
            echo "No merged branches to clean up" >> "$GITHUB_STEP_SUMMARY"
            echo "merged_count=0" >> "$GITHUB_OUTPUT"
          fi
          {
            echo '```'
            echo "### Stale Branches (>${{ inputs.branch_retention_days }} days)"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
          stale_date=$(date -d "${{ inputs.branch_retention_days }} days ago" +%s)
          mapfile -t branches < <(git branch -r | grep -v '\->' | sed 's/origin\///')
          for branch in "${branches[@]}"; do
            [[ $branch == "$default_branch" || $branch == "$current_branch" ]] && continue
            last_commit_date=$(git log -1 --format=%ct "origin/$branch" 2>/dev/null || echo "0")
            if [[ $last_commit_date -lt $stale_date && $last_commit_date != "0" ]]; then
              days_old=$(( ($(date +%s) - last_commit_date) / 86400 ))
              echo "$branch (${days_old} days old)" >> "$GITHUB_STEP_SUMMARY"
            fi
          done
          echo '```' >> "$GITHUB_STEP_SUMMARY"
      - name: Repository Statistics (After)
        if: always()
        run: |
          set -euo pipefail
          {
            echo "## Repository Statistics (After Maintenance)"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
          while IFS=': ' read -r key value; do
            case $key in
              count) object_count=$value ;;
              in-pack) pack_count=$value ;;
              size-pack) repo_size=$value ;;
            esac
          done < <(git count-objects -v | grep -E '^(count|in-pack|size-pack):')
          {
            echo "Objects (loose): $object_count"
            echo "Objects (packed): $pack_count"
            echo "Repository size: ${repo_size} KiB"
            echo ""
          } >> "$GITHUB_STEP_SUMMARY"
          before_size=${{ steps.stats-before.outputs.repo_size }}
          if [[ $before_size -gt 0 ]]; then
            size_diff=$((before_size - repo_size))
            if [[ $size_diff -gt 0 ]]; then
              size_percent=$(awk "BEGIN {printf \"%.2f\", ($size_diff / $before_size) * 100}")
              echo "✓ Size reduced by ${size_diff} KiB (${size_percent}%)" >> "$GITHUB_STEP_SUMMARY"
            elif [[ $size_diff -lt 0 ]]; then
              echo "Repository size increased by $((size_diff * -1)) KiB" >> "$GITHUB_STEP_SUMMARY"
            else
              echo "Repository size unchanged" >> "$GITHUB_STEP_SUMMARY"
            fi
          fi
          echo '```' >> "$GITHUB_STEP_SUMMARY"
      - name: Maintenance Summary
        if: always()
        run: |-
          {
            echo "## Maintenance Summary"
            echo "Completed maintenance tasks:"
            echo ""
            echo "- [x] Repository statistics collected"
          } >> "$GITHUB_STEP_SUMMARY"
          if [[ "${{ inputs.verify_integrity }}" == "true" ]]; then
            mark="x"
          else
            mark=" "
          fi
          echo "- [$mark] Integrity verification" >> "$GITHUB_STEP_SUMMARY"
          if [[ "${{ inputs.run_prune }}" == "true" ]]; then
            mark="x"
          else
            mark=" "
          fi
          echo "- [$mark] Prune unreachable objects" >> "$GITHUB_STEP_SUMMARY"
          if [[ "${{ inputs.run_gc }}" == "true" ]]; then
            mark="x"
          else
            mark=" "
          fi
          echo "- [$mark] Garbage collection" >> "$GITHUB_STEP_SUMMARY"
          if [[ "${{ inputs.optimize_repo }}" == "true" ]]; then
            mark="x"
          else
            mark=" "
          fi
          echo "- [$mark] Repository optimization" >> "$GITHUB_STEP_SUMMARY"
          if [[ "${{ inputs.cleanup_branches }}" == "true" ]]; then
            mark="x"
          else
            mark=" "
          fi
          echo "- [$mark] Branch cleanup analysis" >> "$GITHUB_STEP_SUMMARY"
          workflow_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          {
            echo ""
            echo "---"
            echo "Automated maintenance from [workflow run]($workflow_url)"
          } >> "$GITHUB_STEP_SUMMARY"
