# Git Maintenance & Cleanup (Reusable Workflow)
#
# Required secrets:
#   - PAT (optional): Personal Access Token with repo scope for enhanced permissions
#     Falls back to github.token if not provided
#
# Security: Uses restricted permissions by default (contents: read)
# Jobs override permissions as needed for write operations

name: Git Maintenance & Cleanup (Reusable)
"on":
  workflow_call:
    inputs:
      run_gc:
        description: Run git garbage collection
        type: boolean
        default: true
        required: false
      run_prune:
        description: Prune unreachable objects older than specified time
        type: boolean
        default: true
        required: false
      prune_expire:
        description: Expiration time for pruning (e.g., "2.weeks.ago", "1.month.ago")
        type: string
        default: 2.weeks.ago
        required: false
      optimize_repo:
        description: Run repository optimization (repack, etc.)
        type: boolean
        default: true
        required: false
      verify_integrity:
        description: Verify repository integrity with git fsck
        type: boolean
        default: true
        required: false
      cleanup_branches:
        description: Clean up merged and stale remote-tracking branches
        type: boolean
        default: false
        required: false
      branch_retention_days:
        description: Days to keep branches without activity before marking as stale
        type: number
        default: 90
        required: false
      aggressive_gc:
        description: Use aggressive garbage collection (slower but more thorough)
        type: boolean
        default: false
        required: false
env:
  GIT_AUTHOR_NAME: github-actions[bot]
  GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
  GIT_COMMITTER_NAME: github-actions[bot]
  GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: false

permissions:
  contents: read
jobs:
  maintenance:
    name: Git Repository Maintenance
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      size_before: ${{ steps.stats-before.outputs.repo_size }}
      size_after: ${{ steps.stats-after.outputs.repo_size }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT || github.token }}
      - name: Repository Statistics (Before)
        id: stats-before
        run: |
          set -euo pipefail
          echo "## Repository Statistics (Before Maintenance)" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          declare -A stats
          while IFS=': ' read -r key value; do
            stats["$key"]="$value"
          done < <(git count-objects -v | grep -E '^(count|in-pack|size-pack):')
          branch_count=$(git branch -r 2>/dev/null | grep -vc '\->' || echo "0")
          cat >> "$GITHUB_STEP_SUMMARY" <<EOF
          Objects (loose): ${stats[count]:-0}
          Objects (packed): ${stats[in-pack]:-0}
          Repository size: ${stats[size-pack]:-0} KiB
          Remote branches: $branch_count
          EOF
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo "repo_size=${stats[size-pack]:-0}" >> "$GITHUB_OUTPUT"
      - name: Verify Repository Integrity
        if: inputs.verify_integrity
        run: |
          set -euo pipefail
          echo "## Repository Integrity Check" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          if git fsck --full --no-progress 2>&1 | tee -a "$GITHUB_STEP_SUMMARY"; then
            echo '```' >> "$GITHUB_STEP_SUMMARY"
            echo "âœ… Repository integrity verified" >> "$GITHUB_STEP_SUMMARY"
          else
            echo '```' >> "$GITHUB_STEP_SUMMARY"
            echo "âš ï¸ Integrity issues detected" >> "$GITHUB_STEP_SUMMARY"
          fi
      - name: Prune Unreachable Objects
        if: inputs.run_prune
        run: |
          set -euo pipefail
          echo "## Pruning Objects (older than ${{ inputs.prune_expire }})" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          git prune --expire="${{ inputs.prune_expire }}" --progress 2>&1 | tee -a "$GITHUB_STEP_SUMMARY" || echo "No objects to prune" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
      - name: Run Garbage Collection
        if: inputs.run_gc
        run: |
          set -euo pipefail
          gc_mode=$([[ "${{ inputs.aggressive_gc }}" == "true" ]] && echo "aggressive" || echo "standard")
          echo "## Garbage Collection ($gc_mode)" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          gc_flags="--prune=now"
          [[ "${{ inputs.aggressive_gc }}" == "true" ]] && gc_flags="$gc_flags --aggressive"
          # shellcheck disable=SC2086
          git gc $gc_flags 2>&1 | tee -a "$GITHUB_STEP_SUMMARY" || true
          echo '```' >> "$GITHUB_STEP_SUMMARY"
      - name: Optimize Repository
        if: inputs.optimize_repo
        run: |
          set -euo pipefail
          echo "## Repository Optimization" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          git maintenance run --task=loose-objects --task=incremental-repack 2>&1 | tee -a "$GITHUB_STEP_SUMMARY" || true
          git repack -a -d --depth=250 --window=250 2>&1 | tee -a "$GITHUB_STEP_SUMMARY" || true
          echo '```' >> "$GITHUB_STEP_SUMMARY"
      - name: Analyze Branches
        if: inputs.cleanup_branches
        run: |
          set -euo pipefail
          git fetch --prune --prune-tags
          default_branch=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "main")
          current_branch=$(git branch --show-current)
          merged_branches=$(git branch -r --merged "origin/$default_branch" 2>/dev/null | \
            grep -vE "(->|$default_branch|$current_branch)" | \
            sed 's/origin\///' | tr -d ' ' || true)
          {
            echo "## Branch Analysis"
            echo "### Merged Branches"
            echo '```'
            if [[ -n "$merged_branches" ]]; then
              echo "$merged_branches"
            else
              echo "No merged branches found"
            fi
            echo '```'
            echo "### Stale Branches (>${{ inputs.branch_retention_days }} days)"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
          stale_date=$(date -d "${{ inputs.branch_retention_days }} days ago" +%s)
          found_stale=false
          while IFS= read -r branch; do
            [[ -z "$branch" || "$branch" == "$default_branch" || "$branch" == "$current_branch" ]] && continue
            last_commit=$(git log -1 --format=%ct "origin/$branch" 2>/dev/null || echo "0")
            if [[ "$last_commit" -lt "$stale_date" && "$last_commit" != "0" ]]; then
              days_old=$(( ($(date +%s) - last_commit) / 86400 ))
              echo "$branch (${days_old} days inactive)" >> "$GITHUB_STEP_SUMMARY"
              found_stale=true
            fi
          done < <(git branch -r | grep -v '\->' | sed 's/origin\///' | tr -d ' ')
          {
            [[ "$found_stale" == "false" ]] && echo "No stale branches found"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
      - name: Repository Statistics (After)
        id: stats-after
        if: always()
        run: |
          set -euo pipefail
          echo "## Repository Statistics (After Maintenance)" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          declare -A stats
          while IFS=': ' read -r key value; do
            stats["$key"]="$value"
          done < <(git count-objects -v | grep -E '^(count|in-pack|size-pack):')
          cat >> "$GITHUB_STEP_SUMMARY" <<EOF
          Objects (loose): ${stats[count]:-0}
          Objects (packed): ${stats[in-pack]:-0}
          Repository size: ${stats[size-pack]:-0} KiB
          EOF
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          # Calculate size difference
          before="${{ steps.stats-before.outputs.repo_size }}"
          before="${before:-0}"
          after=${stats[size-pack]:-0}
          if [[ $before -gt 0 && $after -gt 0 ]]; then
            diff=$((before - after))
            if [[ $diff -gt 0 ]]; then
              pct=$(awk "BEGIN {printf \"%.1f\", ($diff / $before) * 100}")
              echo "âœ… Size reduced by ${diff} KiB (${pct}%)" >> "$GITHUB_STEP_SUMMARY"
            elif [[ $diff -lt 0 ]]; then
              echo "ðŸ“ˆ Size increased by $((-diff)) KiB" >> "$GITHUB_STEP_SUMMARY"
            else
              echo "âž¡ï¸ Size unchanged" >> "$GITHUB_STEP_SUMMARY"
            fi
          fi
          echo "repo_size=$after" >> "$GITHUB_OUTPUT"
      - name: Maintenance Summary
        if: always()
        env:
          VERIFY: ${{ inputs.verify_integrity }}
          PRUNE: ${{ inputs.run_prune }}
          GC: ${{ inputs.run_gc }}
          OPTIMIZE: ${{ inputs.optimize_repo }}
          BRANCHES: ${{ inputs.cleanup_branches }}
        run: |
          mark() { [[ "$1" == "true" ]] && echo "x" || echo " "; }
          cat >> "$GITHUB_STEP_SUMMARY" <<EOF
          ## Maintenance Summary

          | Task | Status |
          |------|--------|
          | Repository statistics | âœ… |
          | Integrity verification | $([ "$VERIFY" = "true" ] && echo "âœ…" || echo "â­ï¸") |
          | Prune unreachable objects | $([ "$PRUNE" = "true" ] && echo "âœ…" || echo "â­ï¸") |
          | Garbage collection | $([ "$GC" = "true" ] && echo "âœ…" || echo "â­ï¸") |
          | Repository optimization | $([ "$OPTIMIZE" = "true" ] && echo "âœ…" || echo "â­ï¸") |
          | Branch analysis | $([ "$BRANCHES" = "true" ] && echo "âœ…" || echo "â­ï¸") |

          ---
          ðŸ”— [Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          EOF
