name: Optimize Images (Reusable)
on:
  workflow_call:
    inputs:
      export_webp:
        description: 'Export images to WebP format'
        type: boolean
        default: true
        required: false
      export_avif:
        description: 'Export images to AVIF format'
        type: boolean
        default: false
        required: false
      replace_original:
        description: 'Replace original images after conversion'
        type: boolean
        default: false
        required: false
      compress_png:
        description: 'Compress PNG images'
        type: boolean
        default: true
        required: false
      compress_jpg:
        description: 'Compress JPG/JPEG images'
        type: boolean
        default: true
        required: false
      compress_svg:
        description: 'Compress SVG images'
        type: boolean
        default: true
        required: false
      quality:
        description: 'Output quality (1-100)'
        type: number
        default: 85
        required: false
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
  pull-requests: write
jobs:
  optimize-images:
    name: Optimize Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - name: Cache Image Tools
        uses: actions/cache@v4
        with:
          path: ~/.cache/image-tools
          key: ${{ runner.os }}-image-tools-v1
      - name: Find Images
        id: find-images
        run: |
          set -euo pipefail
          shopt -s nullglob globstar
          mapfile -t images < <(
            find . -type f \( \
              -iname '*.png' -o \
              -iname '*.jpg' -o \
              -iname '*.jpeg' -o \
              -iname '*.gif' -o \
              -iname '*.svg' \
            \) ! -path '*/.git/*' ! -path '*/.cache/*' ! -path '*/node_modules/*'
          )
          echo "image_count=${#images[@]}" >> "$GITHUB_OUTPUT"
          {
            echo "## Images Found"
            echo "Found ${#images[@]} images to process"
          } >> "$GITHUB_STEP_SUMMARY"
      - name: Compress and Convert Images
        id: compress
        if: steps.find-images.outputs.image_count > 0
        uses: stellasoftio/image-optimizer-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          export-webp: ${{ inputs.export_webp }}
          export-avif: ${{ inputs.export_avif }}
          compress-png: ${{ inputs.compress_png }}
          compress-svg: ${{ inputs.compress_svg }}
          compress-jpg: ${{ inputs.compress_jpg }}
          compress-webp: true
          compress-avif: true
          replace-original-after-export-webp: ${{ inputs.replace_original }}
          webp-quality: ${{ inputs.quality }}
          avif-quality: ${{ inputs.quality }}
      - name: Remove Originals
        if: steps.compress.outputs.changes_detected == 'true' && inputs.replace_original
        run: |
          set -euo pipefail
          shopt -s nullglob globstar
          removed=0
          # Remove originals for AVIF
          [[ "${{ inputs.export_avif }}" == "true" ]] && {
            for avif in **/*.avif; do
              base="${avif%.avif}"
              for ext in png jpg jpeg gif; do
                [[ -f ${base}.${ext} ]] && { rm -v "${base}.${ext}"; removed=$((removed + 1)); }
              done
            done
          }
          # Remove originals for WebP
          [[ "${{ inputs.export_webp }}" == "true" ]] && {
            for webp in **/*.webp; do
              base="${webp%.webp}"
              for ext in png jpg jpeg gif; do
                [[ -f ${base}.${ext} ]] && { rm -v "${base}.${ext}"; removed=$((removed + 1)); }
              done
            done
          }
          {
            echo "## Originals Removed"
            echo "Removed $removed original files"
          } >> "$GITHUB_STEP_SUMMARY"
      - name: Calculate Savings
        if: steps.compress.outputs.changes_detected == 'true'
        id: savings
        run: |
          set -euo pipefail
          total_before=$(git diff HEAD --numstat | awk '{sum += $2} END {print sum+0}')
          total_after=$(git diff HEAD --numstat | awk '{sum += $1} END {print sum+0}')
          [[ $total_before -gt 0 ]] && {
            savings=$(awk "BEGIN {printf \"%.0f\", (($total_before - $total_after) * 100 / $total_before)}")
            echo "savings_percent=$savings" >> "$GITHUB_OUTPUT"
            {
              echo "## Optimization Results"
              echo "- **Space saved**: ~${savings}%"
              echo "- **Files modified**: $(git diff --name-only | wc -l)"
            } >> "$GITHUB_STEP_SUMMARY"
          }
      - name: Commit and Push
        if: steps.compress.outputs.changes_detected == 'true' && github.event.pull_request.head.repo.full_name == github.repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(img): optimize images [skip ci]'
          branch: ${{ github.head_ref || github.ref_name }}
          commit_user_name: 'image-optimizer-bot[bot]'
          commit_user_email: 'image-optimizer-bot[bot]@users.noreply.github.com'
          file_pattern: '*.png *.jpg *.jpeg *.gif *.svg *.webp *.avif'
      - name: Comment on PR
        if: steps.compress.outputs.changes_detected == 'true' && github.event_name == 'pull_request' && steps.savings.outputs.savings_percent != ''
        uses: actions/github-script@v7
        with:
          script: |
            const savings = '${{ steps.savings.outputs.savings_percent }}';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Image Optimization Complete\n\n- Space saved: ~${savings}%\n- Images processed successfully`
            });
