name: Shell Lint (Reusable)

on:
  workflow_call:
    inputs:
      exclude_pattern:
        description: 'Regex pattern to exclude files/directories'
        type: string
        default: '(^|/)\.(git|cache|claude)(/|$)'
        required: false
      shellcheck_severity:
        description: 'Minimum severity level for ShellCheck (error, warning, info, style)'
        type: string
        default: 'style'
        required: false
      shfmt_indent:
        description: 'Number of spaces for indentation'
        type: number
        default: 2
        required: false
      apply_fixes:
        description: 'Apply automatic fixes'
        type: boolean
        default: true
        required: false
      commit_changes:
        description: 'Commit and push fixes'
        type: boolean
        default: true
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  lint:
    name: Shell Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}

      - name: Cache Tools
        id: cache-tools
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/bin/shellharden
            ~/.cache/shellcheck
          key: ${{ runner.os }}-shell-tools-v1

      - name: Install ShellCheck and shfmt
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y shellcheck shfmt

      - name: Install shellharden
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          curl -sfL https://github.com/anordal/shellharden/releases/latest/download/shellharden-x86_64-unknown-linux-gnu.tar.gz | \
            sudo tar xz -C /usr/local/bin shellharden
          shellharden --version

      - name: Find Shell Files
        id: find-files
        env:
          EXCLUDE_PATTERN: ${{ inputs.exclude_pattern }}
        run: |
          set -euo pipefail
          shopt -s nullglob globstar

          mapfile -t files < <(
            {
              find . -type f \( -name '*.sh' -o -name '*.bash' -o -name '*bashrc' -o -name '*profile' -o -name 'bash_*' \)
              find . -type f -executable -exec sh -c 'head -n1 "$1" | grep -qE "^#!/.*(bash|sh)"' _ {} \; -print
            } | grep -vE "$EXCLUDE_PATTERN" | sort -u
          )

          echo "file_count=${#files[@]}" >> "$GITHUB_OUTPUT"
          printf '%s\n' "${files[@]}" > /tmp/shell_files.txt

          echo "## Shell Files Found" >> $GITHUB_STEP_SUMMARY
          echo "Found ${#files[@]} shell files to lint" >> $GITHUB_STEP_SUMMARY

      - name: Run ShellCheck
        if: steps.find-files.outputs.file_count > 0
        env:
          SHELLCHECK_OPTS: "--source-path=SCRIPTDIR --external-sources --check-sourced --shell=bash --severity=${{ inputs.shellcheck_severity }}"
        run: |
          set -euo pipefail
          failed=0
          while IFS= read -r file; do
            echo "Checking: $file"
            shellcheck "$file" || ((failed++))
          done < /tmp/shell_files.txt

          echo "## ShellCheck Results" >> $GITHUB_STEP_SUMMARY
          echo "- Files checked: $(wc -l < /tmp/shell_files.txt)" >> $GITHUB_STEP_SUMMARY
          echo "- Files with issues: $failed" >> $GITHUB_STEP_SUMMARY

          exit 0  # Don't fail on shellcheck issues if we're auto-fixing

      - name: Apply Fixes
        if: inputs.apply_fixes && steps.find-files.outputs.file_count > 0
        env:
          SHELLCHECK_OPTS: "--source-path=SCRIPTDIR --external-sources --check-sourced --shell=bash --severity=${{ inputs.shellcheck_severity }}"
        run: |
          set -euo pipefail
          shopt -s nullglob

          while IFS= read -r file; do
            echo "Fixing: $file"
            # Apply shellharden
            shellharden --replace "$file" 2>/dev/null || true
            # Apply shellcheck fixes
            shellcheck -f diff "$file" 2>/dev/null | patch -Np1 2>/dev/null || true
            # Apply shfmt formatting
            shfmt -i ${{ inputs.shfmt_indent }} -s -ln bash -w "$file" 2>/dev/null || true
          done < /tmp/shell_files.txt

      - name: Check for Changes
        id: check-changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes_detected=true" >> "$GITHUB_OUTPUT"
            echo "## Changes Detected" >> $GITHUB_STEP_SUMMARY
            echo '```diff' >> $GITHUB_STEP_SUMMARY
            git diff --stat >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "changes_detected=false" >> "$GITHUB_OUTPUT"
            echo "No changes needed" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Commit and Push
        if: inputs.commit_changes && steps.check-changes.outputs.changes_detected == 'true' && github.event.pull_request.head.repo.full_name == github.repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: apply shell linting fixes [skip ci]'
          branch: ${{ github.head_ref || github.ref_name }}
          commit_user_name: 'shellcheck-bot[bot]'
          commit_user_email: 'shellcheck-bot[bot]@users.noreply.github.com'
