name: Submodule Update (Reusable)
on:
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Update submodules
        id: update
        run: |
          set -e
          git submodule sync --recursive
          git submodule update --init --recursive --remote --merge --filter=blob:none
          git maintenance run --quiet
          [[ -n $(git status --porcelain) ]] && echo "changes_detected=true" >> "$GITHUB_OUTPUT" || echo "changes_detected=false" >> "$GITHUB_OUTPUT"

      - name: Create PR
        if: steps.update.outputs.changes_detected == 'true'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: "chore(submodules): update to latest"
          branch: "chore/submodule-updates"
          create_pull_request: true
          pull_request_title: "chore: update submodules"
          pull_request_body: |
            Automated submodule update from [workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
