# Unified Linters (Reusable Workflow)
#
# Required secrets:
#   - PAT (optional): Personal Access Token with repo scope
#     Falls back to github.token if not provided
#
# Security: Uses restricted permissions by default (contents: read)
# Jobs override permissions as needed for commit/PR operations

name: Unified Linters (Reusable)
"on":
  workflow_dispatch:
  workflow_call:
    inputs:
      enable_shellcheck:
        description: Enable ShellCheck linting
        type: boolean
        default: true
        required: false
      enable_megalinter:
        description: Enable MegaLinter (comprehensive multi-language linting)
        type: boolean
        default: false
        required: false
      enable_reviewdog:
        description: Enable Reviewdog for PR comments
        type: boolean
        default: true
        required: false
      validate_all_codebase:
        description: Validate entire codebase (not just diff)
        type: boolean
        default: false
        required: false
      exclude_paths:
        description: Paths to exclude from linting (glob patterns for ShellCheck)
        type: string
        default: "*/.git/*,./.cache/*,./.claude/*,node_modules/*"
        required: false
      exclude_dirs:
        description: Directories to exclude from MegaLinter (comma-separated)
        type: string
        default: ".github,.git,.cache,node_modules"
        required: false
      apply_fixes:
        description: Apply automatic fixes
        type: boolean
        default: true
        required: false
      megalinter_config:
        description: Path to MegaLinter config file
        type: string
        default: ".megalinter.yml"
        required: false
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  DEBIAN_FRONTEND: noninteractive
  LC_ALL: C

jobs:
  shellcheck-reviewdog:
    name: ShellCheck (Reviewdog)
    runs-on: ubuntu-latest
    if: inputs.enable_shellcheck && inputs.enable_reviewdog
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          token: ${{ secrets.PAT || github.token }}
      - name: Run ShellCheck via Reviewdog
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.PAT || github.token }}
          reporter: github-pr-review
          level: warning
          path: "."
          pattern: |
            *.sh
            *.bash
            .bashrc
            bash_*
          exclude: ${{ inputs.exclude_paths }}
          check_all_files_with_shebangs: "true"
          shellcheck_flags: "-x -s bash -S warning"
  shellcheck-fix:
    name: ShellCheck (Auto-fix)
    runs-on: ubuntu-latest
    if: inputs.enable_shellcheck && inputs.apply_fixes
    continue-on-error: true
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          token: ${{ secrets.PAT || github.token }}
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - name: Find Shell Files
        id: find-files
        run: |
          set -euo pipefail; shopt -s nullglob globstar
          mapfile -t files < <(
            {
              find . -type f \( -name '*.sh' -o -name '*.bash' -o -name '.bashrc' -o -name 'bash_*' \) \
                ! -path '*/.git/*' ! -path '*/.cache/*' ! -path '*/node_modules/*'
              find . -type f -executable \
                ! -path '*/.git/*' ! -path '*/.cache/*' ! -path '*/node_modules/*' \
                -exec sh -c 'head -n1 "$1" | grep -qE "^#!/.*(bash|sh)"' _ {} \; -print
            } | sort -u
          )
          echo "file_count=${#files[@]}" >> "$GITHUB_OUTPUT"
          printf '%s\n' "${files[@]}" > /tmp/shell_files.txt
          {
            echo "## Shell Files Found"; echo "Found ${#files[@]} shell files"
          } >> "$GITHUB_STEP_SUMMARY"
      - name: Apply ShellCheck Fixes
        if: steps.find-files.outputs.file_count > 0
        run: |
          set -euo pipefail
          fixed=0
          while IFS= read -r file; do
            [[ -f $file ]] && {
              shellcheck -f diff "$file" 2>/dev/null | patch -Np1 2>/dev/null && fixed=$((fixed + 1))
            }; done < /tmp/shell_files.txt
          {
            echo "## ShellCheck Fixes Applied"; echo "Fixed $fixed files"
          } >> "$GITHUB_STEP_SUMMARY"
      - name: Commit ShellCheck Fixes
        if: >-
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name == github.repository
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: ${{ github.head_ref || github.ref }}
          commit_message: "style: apply shellcheck fixes [skip ci]"
          commit_user_name: shellcheck-bot[bot]
          commit_user_email: shellcheck-bot[bot]@users.noreply.github.com
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    if: inputs.enable_megalinter
    permissions:
      contents: write
      issues: write
      pull-requests: write
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          token: ${{ secrets.PAT || github.token }}
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter@v9
        env:
          VALIDATE_ALL_CODEBASE: ${{ inputs.validate_all_codebase }}
          GITHUB_TOKEN: ${{ secrets.PAT || github.token }}
          APPLY_FIXES: ${{ inputs.apply_fixes && 'all' || 'none' }}
          MEGALINTER_CONFIG: ${{ inputs.megalinter_config }}
          FILTER_REGEX_EXCLUDE: ${{ inputs.exclude_dirs }}
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
      - name: Archive MegaLinter Reports
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: megalinter-reports
          path: |
            megalinter-reports
            mega-linter.log
          retention-days: 7
      - name: Create MegaLinter Job Summary
        if: always()
        run: |
          {
            echo "## MegaLinter Results"
            echo "- **Status**: ${{ steps.ml.outcome }}"
            echo "- **Repository**: ${{ github.repository }}"
            echo "- **Branch**: ${{ github.ref_name }}"; echo ""
          } >> "$GITHUB_STEP_SUMMARY"
          if [[ -f megalinter-reports/summary.md ]]; then
            cat megalinter-reports/summary.md >> "$GITHUB_STEP_SUMMARY"
          fi
      - name: Commit MegaLinter Fixes
        if: >-
          steps.ml.outputs.has_updated_sources == 1 &&
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name == github.repository
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "style: apply MegaLinter fixes [skip ci]"
          branch: ${{ github.head_ref || github.ref_name }}
          commit_user_name: megalinter-bot[bot]
          commit_user_email: megalinter-bot[bot]@users.noreply.github.com
